name: Nightly Build and Deploy

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Test
        run: |
          docker build -t cs686-midterm:latest .
          docker run --rm cs686-midterm:latest npm run test

      - name: Push to Docker Hub
        run: |
          docker tag cs686-midterm:latest ${{ secrets.DOCKER_USERNAME }}/cs686-midterm:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cs686-midterm:latest